### ISSUE TITLE
'lib/9606/9606.protein.info.txt.gz' does not exist or is non-readable

### ISSUE THREAD

**Issue by Miachol** [martinry/ProteoMill#3]
Hi,

When I try to deploy the local version (https://shiny.hiplot.com.cn/proteomill), an unexpected error occurred: 'Warning: Error in data.table::fread: File 'lib/9606/9606.protein.info.txt.gz' does not exist or is non-readable' . 

How can I resolve it?

Best wishes,

Jianfeng

**Comment by martinry** [comment]
Hi Jianfeng!

I just made some updates to make it easier to run ProteoMill locally. Fetch the new changes, then, using RStudio, _source_ the file "taxonomy.R". This script collects all the necessary external data. Once this is done you should be able to run the app. Let me know how it goes!

Best,
Martin

**Comment by Miachol** [comment]
Thanks, it is working now.
